# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='AlertaActuador',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MicroControlador',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
            ],
        ),
    ]
