# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170926_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tipo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ubicacion'),
        ),
    ]
