# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170926_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='idSensor',
            field=models.BigIntegerField(default=0, verbose_name='idSensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('idSensor', 'time')]),
        ),
    ]
