# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170926_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorUbicacion',
            fields=[
                ('idSensor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tipo')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ubicacion')),
            ],
        ),
        migrations.AlterField(
            model_name='rango',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='idSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SensorUbicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='ubicacion',
        ),
    ]
