 # -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170927_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='time',
            field=models.TimeField(default='06:00', verbose_name='time'),
        ),
    ]
