# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170927_0933'),
        ('dashboard', '0012_auto_20170927_1203'),
    ]

    operations = [
    ]
