# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_merge_20170927_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaActuador',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MicroControlador',
            fields=[
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='idSensor',
        ),
        migrations.RemoveField(
            model_name='sensorubicacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='sensorubicacion',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='subreporte',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='reportes',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='idUbicacion',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='time',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='tipoAlerta',
        ),
        migrations.RemoveField(
            model_name='rango',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rango',
            name='valorMax',
        ),
        migrations.RemoveField(
            model_name='rango',
            name='valorMin',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='zona',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorUbicacion',
        ),
        migrations.DeleteModel(
            name='SubReporte',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
